import { TOP_TEN_API_ENDPOINT, FORUM_BASE_URL } from '../../../constants';

const { fetchFactory } = require('../../request');

export const UPDATE_FORUM_APPS = 'UPDATE_FORUM_APPS';
export const UPDATE_FORUM_APPS_SUCCESS = 'UPDATE_FORUM_APPS_SUCCESS';
export const UPDATE_FORUM_FAILIURE = 'UPDATE_FORUM_APPS_FAILIURE';

export const UPDATE_FORUM_POSTS = 'UPDATE_FORUM_POSTS';
export const UPDATE_FORUM_POSTS_SUCCESS = 'UUPDATE_FORUM_POSTS_SUCCESS';
export const UPDATE_FORUM_POSTS_FAILIURE = 'UPDATE_FORUM_POSTSFAILIURE';


export const UPDATE_FORUM_THREAD = 'UPDATE_FORUM_THREAD';
export const UPDATE_FORUM_THREAD_SUCCESS = 'UPDATE_FORUM_THREAD_SUCCESS';
export const UPDATE_FORUM_THREAD_FAILIURE = 'UPDATE_FORUM_THREAD_FAILIURE';

export const UPDATE_FORUM_COMMENTS = 'UPDATE_FORUM_COMMENTS';
export const UPDATE_FORUM_COMMENTS_SUCCESS = 'UPDATE_FORUM_COMMENTS_SUCCESS';
export const UPDATE_FORUM_COMMENTS_FAILIURE = 'UPDATE_FORUM_COMMENTS_FAILIURE';

const REQUEST_METHODS = {
  GET: 'get',
  POST: 'post',
  PUT: 'put',
  DELETE: 'delete'
};

// GETS
export const fetchForumApps = fetchFactory(REQUEST_METHODS.GET, UPDATE_FORUM_APPS, UPDATE_FORUM_APPS_SUCCESS, UPDATE_FORUM_FAILIURE);
export const fetchForumPosts = fetchFactory(REQUEST_METHODS.GET, UPDATE_FORUM_POSTS, UPDATE_FORUM_POSTS_SUCCESS, UPDATE_FORUM_POSTS_FAILIURE);
export const fetchForumComments = fetchFactory(REQUEST_METHODS.GET, UPDATE_FORUM_COMMENTS, UPDATE_FORUM_COMMENTS_SUCCESS, UPDATE_FORUM_COMMENTS_FAILIURE);

// PUTS
export const updateForumComments = fetchFactory(REQUEST_METHODS.PUT, UPDATE_FORUM_COMMENTS, UPDATE_FORUM_COMMENTS_SUCCESS, UPDATE_FORUM_COMMENTS_FAILIURE);
